### ISSUE TITLE
Adding more features and upgrading the style

### ISSUE THREAD

**Issue by Soumyajit2825** [Soumyajit2825/TO-DO-LIST#1]
**Anyone can contribute in it**

**Comment by Soumyajit2825** [comment]
Ok done
give a ss after your work

**Comment by Soumyajit2825** [comment]
Yeah sure. just put a screen shot before doing PR

**Comment by Urmilasc** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/97338915/194471870-acdf0dd9-e4ff-450a-8b93-a4a6981760c3.png)
hello , here the screenshot , please let me know what to do next

**Comment by Soumyajit2825** [comment]
NICE job!!!!Do PR i will merge it sure

**Comment by Urmilasc** [comment]
Hello  , actually I am very new to github . I created a pull request but
didn't know what to do next .. can you please let me know that you are able
too see my pull request in your github repo?

**Comment by Soumyajit2825** [comment]
Yeah I can see it but it has some merge conflicts issues

**Comment by Soumyajit2825** [comment]
yes

**Comment by pnkjxmwl** [comment]
Hey @Soumyajit2825  Would You like to pull request ,I suppose that you have seen my work
