### ISSUE TITLE
Scroll Not Functioning in Todo Website

### ISSUE THREAD

**Issue by Soumojitshome2023** [Soumyajit2825/TO-DO-LIST#104]
## Problem:
The scrolling functionality on the Todo website is not working as expected, hindering the user's ability to navigate through the content seamlessly.

## Expected Behavior:
Scrolling should allow users to smoothly move through the tasks and other content on the Todo website.

## Steps to Reproduce:

1. Open the Todo website.
2. Attempt to scroll through the tasks or other content.
## Current Behavior:
The scrolling action does not respond or behaves unexpectedly.

**Comment by Soumojitshome2023** [comment]
please assign me this issue

**Comment by Soumyajit2825** [comment]
![image](https://github.com/Soumyajit2825/TO-DO-LIST/assets/100519291/6e2f2920-d0f1-439a-a8a6-961bdc4df315)

It's working fine!

**Comment by Soumojitshome2023** [comment]
but not look good on mobile screen

![image](https://github.com/Soumyajit2825/TO-DO-LIST/assets/121761154/6a75e6d0-9c59-4f2a-8194-580a7db65a29)

**Comment by Soumojitshome2023** [comment]
yas yas , pls assign me
