### ISSUE TITLE
Enhance Design of Completed Checkbox in Todo Web App

### ISSUE THREAD

**Issue by Soumojitshome2023** [Soumyajit2825/TO-DO-LIST#107]
## Current Design:
The completed checkbox in the todo web app currently lacks visual appeal or does not align with the overall design language.

## Expected Design:
Propose a new design or improvement for the completed checkbox that enhances user experience and aligns with the app's aesthetics.

## Design Elements:

Visual Harmony: Ensure that the new design complements the overall design of the todo web app.

User-Friendly: Optimize the design for clear user understanding and interaction.

## Steps to Reproduce:

1. Open the todo web app.
2. Locate the completed checkbox on a task.
3. Observe the current design and imagine the proposed changes.

## Screenshot:
![image](https://github.com/Soumyajit2825/TO-DO-LIST/assets/121761154/64f4e066-f6aa-4c37-812c-7100cfd752d7)

Thank You @Soumyajit2825

**Comment by Soumyajit2825** [comment]
not needed!
