### ISSUE TITLE
Add Sign in and Sign up page 

### ISSUE THREAD

**Issue by rko0211** [Soumyajit2825/TO-DO-LIST#113]
### Describe the feature

Add Sign in and Sign up page 

### It should be implemented because

As this application is useful for every individual people so it should have sign-in and Sign-Up functionality 

### Would you like to work on this issue?(Under Aperture'24)

None

**Comment by Soumyajit2825** [comment]
@rko0211 first finish the assigned 2 tasks!

**Comment by Soumyajit2825** [comment]
It's not needed right now!!
