### ISSUE TITLE
View All option

### ISSUE THREAD

**Issue by YooAshu** [Soumyajit2825/TO-DO-LIST#116]
### Describe the feature

view all option to view all tasks as cards 

### It should be implemented because

because it will be better for user 

### Additional context

clicking on view all, a box of same size of the working box will be visible and it will contains all tasks as card

### Would you like to work on this issue?(Under Aperture'24)

Yes

**Comment by Soumyajit2825** [comment]
@YooAshu do PR before 12 AM if completed or will be invalid
