### ISSUE TITLE
Add delete all option for Completed tasks

### ISSUE THREAD

**Issue by rko0211** [Soumyajit2825/TO-DO-LIST#118]
### Describe the feature

When user completed any task it goes into COMPLETED box in this Box there should be an option to delete all task at once rather delete them manually.

### It should be implemented because

It will make good User Experience 

### Additional context

Kindly review my issue and assign me this task.

### Would you like to work on this issue?(Under Aperture'24)

Yes

**Comment by Soumyajit2825** [comment]
Not needed there is already reset button
