### ISSUE TITLE
Following proper semantics

### ISSUE THREAD

**Issue by Shitanshukumar607** [Soumyajit2825/TO-DO-LIST#119]
### Describe your issue

Not proper semantics since the second svg with the class _waves_ is outside any semantic element

### Steps to reproduce

1. Create a footer tag 
2. Put the second svg in the footer tag just like how first svg is in header tag

### Put here any screenshots or videos (optional)

![image](https://github.com/user-attachments/assets/b40fdf9b-dc6e-49b9-a147-684084faf57c)
![image](https://github.com/user-attachments/assets/bf5828ca-31ae-4ada-a211-9adddf99b341)

### Would you like to work on this issue?(under Aperture'24)

Yes

**Comment by Shitanshukumar607** [comment]
Can i get assigned to fix this? This is my first time creating a issue

**Comment by Soumyajit2825** [comment]
This Program is now closed - Apertre'24 
Apertre'25 will be there from Jan - 3, 2025
You can work then

**Comment by Shitanshukumar607** [comment]
Alright
