### ISSUE TITLE
Update Read Me and add Contributing.md 

### ISSUE THREAD

**Issue by pnkjxmwl** [Soumyajit2825/TO-DO-LIST#12]
Update the Read me file as it contains wrong clone git link. and also add  Contributing.md  that contains all users who contributed.

**Comment by Soumyajit2825** [comment]
OK go for it

**Comment by pnkjxmwl** [comment]
![conte](https://user-images.githubusercontent.com/81282394/194690409-d5f05ebf-968c-47e0-a979-ce8e3a25b355.PNG)
Added This And a Contributors.json file which contains all contributors
