### ISSUE TITLE
Want to add a background image 

### ISSUE THREAD

**Issue by SOUMYADIP76** [Soumyajit2825/TO-DO-LIST#14]
Want to add a background image under hacktoberfest event @Soumyajit2825

**Comment by Soumyajit2825** [comment]
Ok do it but make sure that no other changes are made by you.
Only add a relevant background-image
Put a screen-shot after your work

**Comment by smitioswal** [comment]
Please assign this to me

**Comment by Soumyajit2825** [comment]
go ahead
