### ISSUE TITLE
Add Website Link in About  

### ISSUE THREAD

**Issue by pnkjxmwl** [Soumyajit2825/TO-DO-LIST#16]
Hey Can You add website link https://soumyajit2825.github.io/TO-DO-LIST/to_do.html to 
About where you have written a simple to-do-list webpage.
So that Any One Simply can checkout website and Contribute Easily

**Comment by Soumyajit2825** [comment]
ok ok added

**Comment by Soumyajit2825** [comment]
@pnkjxmwl Thanks for your suggestion

**Comment by pnkjxmwl** [comment]
Bro Not there ,Where tags are showiing 
![dd](https://user-images.githubusercontent.com/81282394/194710512-d297949a-5c91-4a67-9d92-95311c2f46e8.PNG)
Here

**Comment by Soumyajit2825** [comment]
ok. I basically never did it. Wait trying

**Comment by Soumyajit2825** [comment]
got it now

**Comment by pnkjxmwl** [comment]
Great .....
