### ISSUE TITLE
In mobile view font size is too big

### ISSUE THREAD

**Issue by AnshuPathak-88825** [Soumyajit2825/TO-DO-LIST#18]
![image](https://user-images.githubusercontent.com/78332454/194748571-af62be5e-ee85-44b5-9945-9bbd47d1910f.png)

**Comment by AnshuPathak-88825** [comment]
Pls assign me this issue

**Comment by Soumyajit2825** [comment]
OK GO AHEAD

**Comment by AnshuPathak-88825** [comment]
pls merge my Pull request @Soumyajit2825

**Comment by AnshuPathak-88825** [comment]
![image](https://user-images.githubusercontent.com/78332454/194750712-1e52724c-6e99-4f16-88ed-1792507617cb.png)

now it's perfect

**Comment by Soumyajit2825** [comment]
Nice job
Give a star to our repo if you find it helpful and enjoyable
