### ISSUE TITLE
Add background image 

### ISSUE THREAD

**Issue by AnshuPathak-88825** [Soumyajit2825/TO-DO-LIST#19]

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue @Soumyajit2825

**Comment by Soumyajit2825** [comment]
Add a relevant back-ground image which is both visible clearly in dark and light mode

**Comment by ShishuSidharth** [comment]
Hey is it available  then please assign this to me

**Comment by Soumyajit2825** [comment]
Sorry but someone is already assigned on it. Search some other issues related with this to-do-list
You can create your own issue

**Comment by Soumyajit2825** [comment]
@AnshuPathak-88825 have u got the bg-image of the project???or still working on it

**Comment by AnshuPathak-88825** [comment]
I'm unable to find relevant  background image 

https://user-images.githubusercontent.com/78332454/194893967-78117a3e-3139-415b-aa12-ab09f3b18b20.mp4

How about it is it UI  looking good ? pls let me know @Soumyajit2825 
then I'll working on it

**Comment by Soumyajit2825** [comment]
It's a not a background image right
JUst a style

**Comment by AnshuPathak-88825** [comment]
I'm not able to find relevant image so  you can assign it to someone else

**Comment by ShishuSidharth** [comment]
Thanks @Soumyajit2825  i will definitely work on it

**Comment by snehadrita** [comment]
assign me this

**Comment by Soumyajit2825** [comment]
@snehadrita yeh budyy

**Comment by jyotika6221** [comment]
Hey if the issue is open, plz assign it to me.

**Comment by Soumyajit2825** [comment]
@jyotika6221 go fot it
