### ISSUE TITLE
Font color isn't visible when we are in dark theme

### ISSUE THREAD

**Issue by AnshuPathak-88825** [Soumyajit2825/TO-DO-LIST#20]
![image](https://user-images.githubusercontent.com/78332454/194749512-491d1c26-2c4a-4c4d-978c-0dd1a84fc160.png)

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by Soumyajit2825** [comment]
@AnshuPathak-88825 ok nice pick!!!!!

**Comment by AnshuPathak-88825** [comment]
@Soumyajit2825 pls merge my pr

**Comment by Soumyajit2825** [comment]
Done
