### ISSUE TITLE
Adding empty todos

### ISSUE THREAD

**Issue by Darainn** [Soumyajit2825/TO-DO-LIST#23]
<img width="850" alt="image" src="https://user-images.githubusercontent.com/55583949/194751515-e48002a6-895d-443c-9837-2b6cfa71dce8.png">
@Soumyajit2825  empty todos are being added can you assign this issue to me and mark as hacktoberfest label

**Comment by Soumyajit2825** [comment]
@Darainn ok go ahead

**Comment by Darainn** [comment]
@Soumyajit2825 can you mark this as hacktoberfest too it is not accepting currently

**Comment by Soumyajit2825** [comment]
I have add the labels dude

**Comment by Darainn** [comment]
@Soumyajit2825 thankyou man you are the best

**Comment by Soumyajit2825** [comment]
Give a star to the repo😇😇😇

**Comment by Darainn** [comment]
done

**Comment by Soumyajit2825** [comment]
Awesome, thanks!
