### ISSUE TITLE
responsive css

### ISSUE THREAD

**Issue by AbdulRaoof13** [Soumyajit2825/TO-DO-LIST#24]
The mood and sun icons are getting on top of adding the todo item bar, please label it as hacktoberfest and assign this to me so I can correct this.

**Comment by AbdulRaoof13** [comment]
![Capture](https://user-images.githubusercontent.com/49991067/194751969-117b59af-1d3b-4a0a-883d-c955f044ff44.PNG)

**Comment by Soumyajit2825** [comment]
OK do one thing label this toogle icon to a side of the page and add a slider button

**Comment by AbdulRaoof13** [comment]
ok

**Comment by Soumyajit2825** [comment]
yeah
