### ISSUE TITLE
Add Scroll in the todo list container

### ISSUE THREAD

**Issue by adnansam110** [Soumyajit2825/TO-DO-LIST#26]
The todo list content goes out of the screen when list increases. Should have a scroll in the todo list container.  @Soumyajit2825 can you assign this to me please under hacktoberfest label

![image](https://user-images.githubusercontent.com/51002433/194752903-a6635a90-68fc-487a-a9ee-b1570f03c2e8.png)

**Comment by Soumyajit2825** [comment]
@adnansam110 yeah sure. Nice issue pick. Go ahead
