### ISSUE TITLE
Dark mode toggle button margin issue

### ISSUE THREAD

**Issue by jsvigneshkanna** [Soumyajit2825/TO-DO-LIST#27]
The dark mode toggle button bottom margin has to be increased as it overlaps with todo input area,

![image](https://user-images.githubusercontent.com/42484705/194753350-1e5461f7-ae41-436e-86dd-a5b53c903751.png)

Please assign this issue to my name,

Appreciate that!

**Comment by Soumyajit2825** [comment]
#24 already assigned this issue to someone else
Thank you for your attention
