### ISSUE TITLE
Modify the TO-Do section and make it more attractive

### ISSUE THREAD

**Issue by Soumyajit2825** [Soumyajit2825/TO-DO-LIST#3]

**Comment by Chaitanya-087** [comment]
i would like to work on this

**Comment by Soumyajit2825** [comment]
go ahead. Kindly add a screen shot after your work and then do PR

**Comment by Chaitanya-087** [comment]
yeah sure

**Comment by Soumyajit2825** [comment]
Best of luck

**Comment by Harikrishna3** [comment]
I'd like to work on this; 
Would you kindly assign it to me?

**Comment by Soumyajit2825** [comment]
@Harikrishna3 yeah sure.. go through it. Kindly add a screen shot of your work and then do a PR

**Comment by 035pratheeksha** [comment]
Can you please assign this to me?

**Comment by Soumyajit2825** [comment]
@035pratheeksha Ok go ahead.

**Comment by Chaitanya-087** [comment]
![image](https://user-images.githubusercontent.com/76115770/194488180-85106458-f2d2-4fd8-b51e-4698019517da.png)

**Comment by Harikrishna3** [comment]
![image](https://user-images.githubusercontent.com/86600101/194491489-3aa103da-60fb-4cfd-b0bd-19307e2b7707.png)

**Comment by Harikrishna3** [comment]
![image](https://user-images.githubusercontent.com/86600101/194496848-558f0e65-8b08-4461-b96b-3702a340d60c.png)

**Comment by Soumyajit2825** [comment]
@Chaitanya-087 merging your PR
@Harikrishna3 Thanks for contributing
