### ISSUE TITLE
Update contrbuting.json

### ISSUE THREAD

**Issue by Soumyajit2825** [Soumyajit2825/TO-DO-LIST#31]
Update the contributors list
add all the names and pictures along the previous ones

**Comment by mehraankush** [comment]
Like any random name and emoji ??

**Comment by Soumyajit2825** [comment]
No no
The person who are contribute in this project and their corresponding profile images
There is already a contributing.json file available
U just have to update that if u know how to do

**Comment by Soumyajit2825** [comment]
@pnkjxmwl Would you like to do the documentation update again??? 😃

**Comment by pnkjxmwl** [comment]
Yeah sure  I will do it

**Comment by Soumyajit2825** [comment]
Rock on! 🔥
