### ISSUE TITLE
alignment of edit delete icons if text length is large

### ISSUE THREAD

**Issue by Darainn** [Soumyajit2825/TO-DO-LIST#35]
<img width="852" alt="image" src="https://user-images.githubusercontent.com/55583949/194755160-c315bf90-cbde-4504-97cc-a00a2f7da552.png">

@Soumyajit2825 assign me this issue to align the icons

**Comment by Darainn** [comment]
@Soumyajit2825 you will have to add hacktoberfest label in all of them to get your repo as a hacktoberfest accepeted.Thanks

**Comment by Soumyajit2825** [comment]
ok thanks for telling this'
I have added labels to all issues and PR's

**Comment by Darainn** [comment]
@Soumyajit2825 you have to add them in completed issues to like the in this one too , for it to get accepted

**Comment by Soumyajit2825** [comment]
yeah. All done
