### ISSUE TITLE
Background Color changes to lightblue in responsive mode

### ISSUE THREAD

**Issue by coding-manuel** [Soumyajit2825/TO-DO-LIST#36]
![image](https://user-images.githubusercontent.com/53911108/194755192-c0290389-1cd0-4071-b641-51c10b0058f4.png)
The background color changes to white in responsive but after changing the color theme changes to white again.
We can either keep it light blue or I can change this behaviour.

**Comment by Soumyajit2825** [comment]
change this behaviour if u can
