### ISSUE TITLE
Improving User Interface

### ISSUE THREAD

**Issue by pnkjxmwl** [Soumyajit2825/TO-DO-LIST#4]
Hy,
i would like to contribute to your repository by improving the user Interface.
If you want to improve UI kindly assign this task to me @Soumyajit2825 
Thank You

**Comment by Soumyajit2825** [comment]
@pnkjxmwl yeah go ahead. Read the README.md file and contribute following that. Don't forget to put a screen shot after your work

**Comment by pnkjxmwl** [comment]
![hacktober](https://user-images.githubusercontent.com/81282394/194493870-422478f3-1df6-4832-8635-88410c37ac01.PNG)

Hy again @Soumyajit2825  Here's  The ScreenShot .Hope You Like It . I tried To make it Simple.

**Comment by Soumyajit2825** [comment]
aha!nice do PR now I will merge it
