### ISSUE TITLE
Misaligned Button and TextInput

### ISSUE THREAD

**Issue by coding-manuel** [Soumyajit2825/TO-DO-LIST#41]
![image](https://user-images.githubusercontent.com/53911108/194756657-0e2f0f14-5c10-49cc-8995-8ae88f6ed0c4.png)
The text Input and the Add button have different heights which should be the same.
Also, the button should have some padding and the font size should be smaller.

**Comment by Soumyajit2825** [comment]
😃 salute to your observation power
