### ISSUE TITLE
cursor should be pointer in theme changer

### ISSUE THREAD

**Issue by AnshuPathak-88825** [Soumyajit2825/TO-DO-LIST#44]
![image](https://user-images.githubusercontent.com/78332454/194758713-80f9bcf5-4dfe-4a23-9d9a-d6f75ba62be6.png)

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by Soumyajit2825** [comment]
You have assigned 2 more issues previously
Solve them dude 1st!!!!!
You can go ahead surely on it

**Comment by AnshuPathak-88825** [comment]
dude I'll solve them today don't worry

**Comment by Soumyajit2825** [comment]
yeah 👍🏻

**Comment by AnshuPathak-88825** [comment]
someone already fixed it so I'm closing it

**Comment by AnshuPathak-88825** [comment]
solve this issue pls merge it

**Comment by Soumyajit2825** [comment]
Done merged
