### ISSUE TITLE
Editing To Do List Allows Blank Value

### ISSUE THREAD

**Issue by darshanshah1996** [Soumyajit2825/TO-DO-LIST#51]
On Editing a List Item added currently we allow the `list item to blank`  although we show validation that `todo list item` cant be blank when we add `new list item`

Would like to add validation for `Edit field` as well

Also currently when we show a validation message `Please enter a todo` we use the `Alert modal` would like to replace it with toaster message on the UI. Let me know your thoughts for a different UI if required for toaster message

Issue Screencast:
https://www.loom.com/share/37423b2420fa43b3ac51e95fc4038d6b

**Comment by darshanshah1996** [comment]
@Soumyajit2825  let me know if i can pick the above issue

**Comment by Soumyajit2825** [comment]
@darshanshah1996 Yeah good issue go for it
Make no other changes
Just fix that bug
