### ISSUE TITLE
Save data to browser's local storage

### ISSUE THREAD

**Issue by aldyadk** [Soumyajit2825/TO-DO-LIST#53]
I wonder what if every user visiting this page will have the capability to save each of their own todo list just by saving it's data to their local storage. I could write some code to achieve that.

**Comment by Soumyajit2825** [comment]
Wow!!
That could be so awesome if u can do it
You can seperated time of the time when the lease of the corresponding user has created their list!!!
Nice feature
Go ahead!!
BEST OF LUCK
