### ISSUE TITLE
bug *

### ISSUE THREAD

**Issue by Soumyajit2825** [Soumyajit2825/TO-DO-LIST#57]
![Screenshot 2022-10-10 185432](https://user-images.githubusercontent.com/100519291/194876766-10d60b53-4716-46b9-8237-033846d5d10d.jpg)
**On adding a huge number of items in the list the toggle theme button is dissapeared 
So if anyone add a scroll button in the to-do list to make the list size fixed in the page it will be very useful**

**Comment by smitioswal** [comment]
assign me please

**Comment by smitioswal** [comment]
![image](https://user-images.githubusercontent.com/92663204/194883909-c3b52c36-57df-4ce6-9d7b-d6b856bb5649.png)
