### ISSUE TITLE
Add a favIcon in new tab that represents todo

### ISSUE THREAD

**Issue by AhmedAli125** [Soumyajit2825/TO-DO-LIST#65]
Add a nice little favIcon that represents a Todo instead of world icon

**Comment by AhmedAli125** [comment]
Can you please assign this issue to me and mark it with a hacktoberfest label. Thankyou

**Comment by abhishekr700** [comment]
@Soumyajit2825 Can I work on this ?

**Comment by Soumyajit2825** [comment]
yeah u can. Just put a screen shot of your work after completing. Then i will assign you in this
