### ISSUE TITLE
Incomplete task show "RED" color and font-family change

### ISSUE THREAD

**Issue by Geeks-Arpan** [Soumyajit2825/TO-DO-LIST#71]
![Screenshot 2023-12-31 191343](https://github.com/Soumyajit2825/TO-DO-LIST/assets/99377659/b98f5422-f8fe-4c00-909e-39ee0794b907)

**Comment by Shreya02k** [comment]
I can contribute to it With more add on features.

**Comment by 123shreyanvi** [comment]
I can do this with add on features to make it more attractive.

**Comment by Soumyajit2825** [comment]
@Geeks-Arpan as this is an easy issue I hope that you will complete it within 1 day! Otherwise it will be assigned to someone else
All the best

**Comment by scriptGenie** [comment]
I have made a pull request addressing this issue in the event it becomes available again.

**Comment by Soumyajit2825** [comment]
> I have made a pull request addressing this issue in the event it becomes available again.

@Geeks-Arpan has opened it first!
So he has the first chance to do the PR on it

**Comment by Soumyajit2825** [comment]
@Geeks-Arpan any update???
