### ISSUE TITLE
Add a colour palette to get various themes except dark and light mode for better interactivity .

### ISSUE THREAD

**Issue by nsrs-78** [Soumyajit2825/TO-DO-LIST#73]
![Screenshot 2024-01-01 212651](https://github.com/Soumyajit2825/TO-DO-LIST/assets/137761848/bf4c6646-70f1-469b-8234-1efe036c6c57)

**Comment by nsrs-78** [comment]
Can I do it for getting the web more attractive? Thank you

**Comment by Soumyajit2825** [comment]
not needed!
But thanks for raising an issues. You can find some other issues.
