### ISSUE TITLE
Add more css and js to make To-Do-List eye catching to the user 

### ISSUE THREAD

**Issue by 123shreyanvi** [Soumyajit2825/TO-DO-LIST#74]
adding animation on scroll
adding Hover feature (transform) etc.
adding css like rotating border of TO-DO box.
adding description to the documentation

**Comment by 123shreyanvi** [comment]
Please do assign this to me ,I can do it with perfection

**Comment by AnuragMalasi** [comment]
I would like to contribute by adding css work to this project.
Please assign this issue to me.
Thanks.

**Comment by Soumyajit2825** [comment]
Closed as completed!
Good job @123shreyanvi

**Comment by 123shreyanvi** [comment]
Thank You !!
