### ISSUE TITLE
Adding a logo, filter option, and reset functionality

### ISSUE THREAD

**Issue by soumili19** [Soumyajit2825/TO-DO-LIST#77]
I've added a logo, but there are currently no filter options to distinguish between completed and pending tasks, and there's also no reset option to start a fresh.

**Comment by Soumyajit2825** [comment]
Someone has already raised an issue for distinguishing pending tasks #71

**Comment by Soumyajit2825** [comment]
@Soumya-2003 any update?

**Comment by Soumya-2003** [comment]
> @Soumya-2003 any update?

Yes, I've added the required functionality and pushed my commited branch and already made a pull request

**Comment by Soumyajit2825** [comment]
> > @Soumya-2003 any update?
> 
> Yes, I've added the required functionality and pushed my commited branch and already made a pull request

Some changes required. Check!

**Comment by Soumya-2003** [comment]
> > > @Soumya-2003 any update?
> > 
> > 
> > Yes, I've added the required functionality and pushed my commited branch and already made a pull request
> 
> Some changes required. Check!

Okay, let me Solve

**Comment by Soumyajit2825** [comment]
Yeah go ahead!
