### ISSUE TITLE
Upgrading button

### ISSUE THREAD

**Issue by Soumyajit2825** [Soumyajit2825/TO-DO-LIST#8]
- [x] Add hover effect in the buttons
- [x] Do some more attractive styles with the buttons

**After your work give a _screenshot_ of your work and then make the PR**

**Comment by vilasrhegde** [comment]
Hey @Soumyajit2825  can I improve this task?

**Comment by Soumyajit2825** [comment]
@vilasrhegde yeah go ahead. Do as told. Don't forget the ss

**Comment by vilasrhegde** [comment]
@Soumyajit2825 I got problem with the images that you used for edit and delete buttons. Can I change them?

**Comment by Soumyajit2825** [comment]
ok do relevant changes with the changes that are mwntioned

**Comment by vilasrhegde** [comment]
@Soumyajit2825 
![image](https://user-images.githubusercontent.com/85540091/194599382-d4950ad0-66c5-4bb1-b55e-2ee1a37282b7.png)
have a look

**Comment by Soumyajit2825** [comment]
Ya nice !!!! Do pr i will merge it

**Comment by vilasrhegde** [comment]
@Soumyajit2825 go on..!
Thank you

**Comment by Soumyajit2825** [comment]
my pleasure
