### ISSUE TITLE
I found a problem in scrolling and completed tasks

### ISSUE THREAD

**Issue by sayanbose-0000** [Soumyajit2825/TO-DO-LIST#80]
+ changing opacity of completed tasks so that everything, along with the checkbox is decrease in opacity (earlier only the text was grayed out, which looked bad against the fully coloured checkbox).
+ Earlier, when the no. of items were large, the entire container scrolled. As a result, the todo count got hidden. I fixed it too.
    - when I fixed the above issue, I saw the scrollbars looked bad on the small box. So, I added new custom scrollbars

**Comment by Soumyajit2825** [comment]
@sayanbose-0000 is this issue completed?

**Comment by sayanbose-0000** [comment]
I added them in the previous PR. You have already accepted it

**Comment by Soumyajit2825** [comment]
Ok cool done!
