### ISSUE TITLE
TO-do section

### ISSUE THREAD

**Issue by Soumyajit2825** [Soumyajit2825/TO-DO-LIST#9]
Make the TO-DO  list view some larger than now.
You can make the to-do list bigger in size

**Put a screen shot of your work and then make PR**

**Comment by HaroonAzhar** [comment]
can I work on this?

**Comment by Soumyajit2825** [comment]
@HaroonAzhar go ahead

**Comment by smitioswal** [comment]
Can I work on this if it's not done yet?

**Comment by Soumyajit2825** [comment]
@smitioswal yeah go ahead

**Comment by smitioswal** [comment]
![image](https://user-images.githubusercontent.com/92663204/194717952-1f829be0-83aa-43ce-a172-f5f8872deb45.png)

**Comment by Soumyajit2825** [comment]
OK

**Comment by Soumyajit2825** [comment]
Do PR now
