### ISSUE TITLE
Adding a congratulatory reward for each complete task and unlocking new features with those rewards.

### ISSUE THREAD

**Issue by Soumili-2004** [Soumyajit2825/TO-DO-LIST#91]
A congratulatory reward in the form of points, coins or diamonds etc. would be nice for every complete task. This could make completing task fun for the user and also motivate him/her to complete all of his to do list.

Also the user can unlock new features like different themes maybe with those rewards.

/*This is just a suggestion to fellow contributors to fix this issue as I'm just beginner to coding and don't know how to fix it*/

**Comment by dipa-ghosh11** [comment]
Hello @Soumyajit2825 I am interested in this issue and i want to fix it.

**Comment by dipa-ghosh11** [comment]
I will make a congratulatory reward after completing each task within assign time and every reward will be added and more 
 new features which will be provided they can use. please assign me for this issue.

**Comment by anushikha29** [comment]
please assign me this issue @Soumyajit2825

**Comment by Soumyajit2825** [comment]
@anushikha29 you have been assigned!
You have 3 days to complete it. after that I will re assign @dipa-ghosh11 to it!

**Comment by rko0211** [comment]
Kindly assign me this task.

**Comment by Souvik34** [comment]
@Soumyajit2825  Assign me the task. I shall deliver it on time

**Comment by Soumyajit2825** [comment]
@anushikha29 any update?
Otherwise I will assign someone else by tonight!

**Comment by rko0211** [comment]
Hey @Soumyajit2825  Assign me this task.

**Comment by Soumyajit2825** [comment]
@rko0211 go ahead!
